# Generated by Django 3.1.6 on 2021-03-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20210312_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
