# Generated by Django 3.1.6 on 2021-03-16 13:19

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_remove_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255, verbose_name='Name'), unique=True),
        ),
    ]
