# Generated by Django 3.1.6 on 2021-03-16 17:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20210316_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.TextField(max_length=1024, verbose_name='Post text'), unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=1024, verbose_name='Post text'),
        ),
    ]
