# Generated by Django 3.1.6 on 2021-03-18 16:21

from django.db import migrations
from django.utils.text import slugify


def gen_identifier(apps, schema_editor):
    Profile = apps.get_model('basic', 'Profile')
    for profile in Profile.objects.all():
        profile.identifier = slugify(f"{profile.first_name} {profile.last_name}")
        profile.save(update_fields=['identifier'])


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_add_identifier_field'),
    ]

    operations = [
        migrations.RunPython(gen_identifier, reverse_code=migrations.RunPython.noop)
    ]
