# Generated by Django 3.1.6 on 2021-03-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_populate_identifier_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identifier',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
